### ISSUE TITLE
donation plugin

### ISSUE THREAD

**Issue by endbase** [ManiaControl/ManiaControl#105]
if donate Error : Creator is not validated proberly caused as an bug of mp4 itself

**Comment by kremsy** [comment]
Have you tried sending 20 planets via ingame letter to the server first?

**Comment by endbase** [comment]
Yeah I have send 1000 planets to server login

**Comment by kremsy** [comment]
definitly a nadeo bug (or wrong validation key)

**Comment by endbase** [comment]
Validation Key is good btw

**Comment by kremsy** [comment]
Its for sure a general mp4 problem, guess it works for noone, open a topic in the mp forum if you have access.
