### ISSUE TITLE
php zip check

### ISSUE THREAD

**Issue by endbase** [ManiaControl/ManiaControl#112]
Is there an way to bypass the PHP ZIP check at start at nc1.eu they don't have it installed so mania controller won't start ! I allready send them a ticket so I waiting for now

**Comment by kremsy** [comment]
Nope, without the php zip libary the autoupdate will fail and the controller will crash, this lib is requried.

**Comment by kremsy** [comment]
And be sure you use newest maniacontrol version

**Comment by endbase** [comment]
Yeah I do but it is so frustrating that I have to wait on the host ! Thx for your reply :)
