### ISSUE TITLE
Stop renaming functions please and sidebarmenumanager

### ISSUE THREAD

**Issue by Designburo** [ManiaControl/ManiaControl#121]
Please stop renaming stuff all the time. You have any idea what a pain it is to follow up on that with 6 plugins!
Btw.. the changes for the Sidebarmenumanager break your own MC plugins
this : 
`$this->maniaControl->getSettingManager()->getSettingValue(SidebarMenuManager::class, SidebarMenuManager::SETTING_MENU_ITEMSIZE);`
now throws fatal errors.

**Comment by kremsy** [comment]
What renamings you mean exactly, most of them where done already 1 year and marked them es deprecated. And most of changes where just done once from.mp3 to mp4, i suggest to use phpstorm which tells you the changes all automatically with viewing your code, sorry for problems.

**Comment by kremsy** [comment]
f
