### ISSUE TITLE
Plugin updates arent shown for disabled plugins (at least queue v0.13 installed, 0.14 not shown as available update)

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#122]

**Comment by kremsy** [comment]
(maybe make a force update button to plugins, to update whatever happens)

**Comment by Designburo** [comment]
Where is 0.14 ? The plugin repository shows 0.13 is the current version ?

**Comment by kremsy** [comment]
okay, seems like bug was that it was not set as active on website, the newest version
