### ISSUE TITLE
What happened with RecordCallback ?

### ISSUE THREAD

**Issue by Vincent-P** [ManiaControl/ManiaControl#136]
Hello,
I'm currently trying to update the Obstacle plugin made by steeffeen.
His plugin doesn't work because it relies on RecordCallback.
So what happened with RecordCallback ? Are there any alternatives or do I have to code it myself ?

**Comment by kremsy** [comment]
There are the new Nadeo callbacks you can directly use, see the Subfolders of the Callback directory.

The RecordCallback has been removed due the new callback structure of nadeo.

**Comment by Vincent-P** [comment]
Okay, I used TrackMania callbacks instead, thanks.
