### ISSUE TITLE
Move the Server annoucements right

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#138]
![grafik](https://cloud.githubusercontent.com/assets/2006941/26316829/c90dc2b0-3f15-11e7-84f1-96ad14eff4bb.png)

put that right of the Serverwidget

**Comment by steeffeen** [comment]
Requires https://github.com/steeffeen/FancyManiaLinks/issues/42
The screenshot shows the "Live Info"

**Comment by steeffeen** [comment]
FML is ready
