### ISSUE TITLE
Dedimania opens 2nd connection on same time requests

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#139]
[22-May-2017 16:26:49 UTC] [ManiaControl NOTICE]: XmlRpc Fault on 'dedimania.SetChallengeTimes': 'Error in method_handler.php(847): Server drakoservmp001 is trying to use session on multiple connections, this is forbidden !!! ()!
File&Line: /home/drakonia/ManiaPlanet4/ManiaControl/plugins/MCTeam/Dedimania/DedimaniaWebHandler.php: 592

If two requests are happen on same time, the dedimania plugin is oppening a second connection for the second request it closes it after, for the dedimania plugin the multi curl probably needs to set to Pipelining or something.

**Comment by Bueddl** [comment]
Reopen due to revert https://github.com/ManiaControl/ManiaControl/commit/edcd18e8f5d907af06c626b710d93b683244375f.
New solution ahead.

**Comment by kremsy** [comment]
Resolved https://github.com/ManiaControl/ManiaControl/commit/ff643c16744e070fc3ed02df1c7743523b50ed5b
