### ISSUE TITLE
WidgetPlugin author login / nick switch

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#142]
make a setting to display nickname of author instead of login

**Comment by axelalex2** [comment]
Well, i thought this would be easy, but unfortunately a custom Script would be required to display the author nickname, so i won't include that feature in the near time.

**Comment by axelalex2** [comment]
748dafa6910ffdf27a3fcc0d6c610501ebee0388
After looking into it, it didn't take too long to figure out. Feature is available now.
