### ISSUE TITLE
Maniacontrol settings

### ISSUE THREAD

**Issue by hunterlue** [ManiaControl/ManiaControl#147]
Hi,

i accidently moved the //settings window too far up, now i cant reach certain settings to undo it, could you help?
![settings_rip](https://cloud.githubusercontent.com/assets/29159705/26752267/346aeb34-484c-11e7-8876-3c68663d889f.JPG)

i tried reinstalling the plugin etc, it just comes back like this again x_x

**Comment by kremsy** [comment]
You could delete the setting out of the database or change the value there,

**Comment by hunterlue** [comment]
in which database should this normally be? i normally dont do stuff there^^

**Comment by hunterlue** [comment]
nvm someone with knowledge of this helped me search through the files, ty for the tip
