### ISSUE TITLE
Couldn't connect to the server: 'Wrong protocol header' 

### ISSUE THREAD

**Issue by XenitoX** [ManiaControl/ManiaControl#149]
When i run ManiaControl.bat i get this error: 
" Couldn't connect to the server: 'Wrong protocol header' "

and i cannot figure out what's wrong. please help 
https://gyazo.com/503aa4026e582db72c9182eda5b3ec65

**Comment by kremsy** [comment]
Are you sure you connecting to the correct port? The Xmlrpc port of your server?

**Comment by XenitoX** [comment]
I got that to work now after finding the right port, thank you, but now i have a new problem. :(

https://gyazo.com/78bd348e37a0b9d8931f8d25ae6aa598

**Comment by kremsy** [comment]
Weired issue, never saw that before but it seems like "extension=php_mbstring.dll" is not enabled on your php, will add it to the requirement check soon

**Comment by XenitoX** [comment]
Enabled it and it worked, but when i joined the server there are no panels or anything. and i got this: 
https://gyazo.com/76c104d5502f6a08a51cee41e682a999
https://gyazo.com/b535f6c4822edb30e111bb2e1822fc01

This is not supposed to be easy i guess

**Comment by kremsy** [comment]
This shows that you restarted the server or something?

**Comment by XenitoX** [comment]
I think i found the problem for the errors. I have 2 servers, and i used the same maniaplanet dedicated server user for both of them. So it stopped the server, and that is when the error occured (Obviously because the server stopped). But i do still not have any panels ingame, but it says in chat that i am using ManiaControl. Do i have to setup panels on my own, if i do where do i find a tutorial for that ?

**Comment by kremsy** [comment]
(set different xmlrpc ports in the config of the dedicated servers)

Panels should show up automatically.

Or wait did you not start the server using the dedicated server software?

**Comment by XenitoX** [comment]
I created a new dedicated server user on maniaplanet for my other server. so that is not a problem anymore. 
this is what i am doing: 
1. Run the startServer.bat file for trackmania2 server. 
2. (after i see that the server is running) Run the .bat file for maniacontrol. 
3. Connecting to the server 

am i doing something wrong ?

**Comment by kremsy** [comment]
Sounds right, make sure if you have multiple servers you use different xml ports.

Ah yeah, you have to add yourserver to masteradmin in servers.xml, aftwards a yellow icon on right side appears, by clicking it, going in plugins menu you can activate the basic plugins:

WidgetPlugin
KarmaPlugin
LocalrecordsPlugin (if Trackmania)
CustomVotesPlugin

**Comment by XenitoX** [comment]
I got it to work kind of.. i activated all the plugins i wanted, but the local Records plugin wont work.
https://gyazo.com/630ccfc49733bfc430775de8d19933ef
and im getting this: data too long for column.. i dont know what it means, or if it is even an error
https://gyazo.com/6ba8e16ca53d7dea6a3f3fd25d25b81d
https://gyazo.com/a60632f34fa95eacc127fb147a5141a0

**Comment by XenitoX** [comment]
Can't get this to work yet :/ the local records plugin wont work, me and my friend have thied driving through many maps to get the records, but nothing shows up on the local records panel.
https://gyazo.com/630ccfc49733bfc430775de8d19933ef

and im also still getting this in the console: 
"
data too long for column 'default' at row 1 in c:\Users\Jonas\Desktop\ManiaControl-master\core\settings\settingManager.php on line 322
"
https://gyazo.com/6dafb5c42cfd9c80acbdfd78f793ee56

**Comment by kremsy** [comment]
1) are you sure you run the server in script mode and be on newest dedicated server software?

2) you enter a too long setting somewhere or some plugin inserting a too long default value, don't know which plugin by having the record

**Comment by kremsy** [comment]
No answer, closed for now.
