### ISSUE TITLE
Issues with maps

### ISSUE THREAD

**Issue by Vincent-P** [ManiaControl/ManiaControl#151]
Hi,
There are some issues related to maps in Obstacle ( however I dont know if it's specific to this mode) :
- The map queue doesn't seem to work
- I can't update maps via MX, I can click on the update button but as soon as I click "check update" I can update the map again.

**Comment by kremsy** [comment]
1) issue, will investigate but Im pretty sure that there are callbacks missing in Obstacle for this if it doesnt work (think BeginPodium / endPodium callback)

2) the map should be updated after clicking once, the update available just shows for a further minute and will than dissapear, as the update check is done by time comparism and only based on minutes I think.

**Comment by Vincent-P** [comment]
Okay, what callbacks are needed ?

**Comment by kremsy** [comment]
The new MP4 callbacks, If obstacle extends ModeShootmania all should be fine.

**Comment by Vincent-P** [comment]
I've updated the obstacle script to extends the ModeShootmania, only the first map queued works

**Comment by kremsy** [comment]
Ive noticed the bug in some other gamemodes as well but couldnt reproduce it, I think it has todo with the timing of the cbs or something.

**Comment by Vincent-P** [comment]
I made some progress, map queue works as expected now, however the update with MX doesnt work 😞

**Comment by kremsy** [comment]
How did you get the mapqueue working?

What exactly does not work.with mx, are there errors in chat?

**Comment by Vincent-P** [comment]
It always show the green icon to update maps

**Comment by kremsy** [comment]
I gonna check today, thanks for report.

**Comment by Vincent-P** [comment]
I think the MX list error is due to the last MX update

**Comment by kremsy** [comment]
Yeah I got noticed that mx fixed this issue by now.

**Comment by kremsy** [comment]
How did you get the queue problem working?

**Comment by Vincent-P** [comment]
I just upgraded the obstacle script to extends ModeShootmania properly

**Comment by kremsy** [comment]
Alright, nice 👍

**Comment by Vincent-P** [comment]
I still have the issue withe the update button displayed when the map is already at latest version

**Comment by kremsy** [comment]
is it also after 1 minute waiting and reopening maplist?

**Comment by Vincent-P** [comment]
Yes

**Comment by kremsy** [comment]
Yeah please, its weired I just tested it  (not in obstacle) and it works as it should

**Comment by Vincent-P** [comment]
Here it is : #join=testobs@obstacle@smokegun

**Comment by kremsy** [comment]
Fixed it already for next update :)

**Comment by Vincent-P** [comment]
Okay great !
