### ISSUE TITLE
Dedimania v0.221

### ISSUE THREAD

**Issue by frozing** [ManiaControl/ManiaControl#154]
Hello i have problem with Dedimania,

**[22-Jun-2017 10:12:51 UTC] [INFO] Try to connect on Dedimania
[22-Jun-2017 10:12:51 UTC] [INFO] Dedimania connection successfully established.**

 when i launch Maniacontrol  its ok but after 3 maps i have error.

" [**ManiaControl NOTICE]: XmlRpc Fault on 'dedimania.SetChallengeTimes': 'Error in method_handler.php(847): Server nova_v_ta is trying to use session on multiple connections, this is forbidden !!! ()!
File&Line: /home/Serveur/Valley_TA/_ManiaControl/plugins/MCTeam/Dedimania/DedimaniaWebHandler.php: 576**

**[22-Jun-2017 10:15:58 UTC] PHP Notice:  XmlRpc Fault on 'dedimania.SetChallengeTimes': 'Error in method_handler.php(847): Server nova_v_ta is trying to use session on multiple connections, this is forbidden !!! ()! in /home/Serveur/Valley_TA/_ManiaControl/plugins/MCTeam/Dedimania/DedimaniaWebHandler.php on line 576 '**

i'm new on Maniacontrol and its very good Inteface

thank you at advance.

frozing

**Comment by kremsy** [comment]
A fix will be provided the next 2-3 days.

**Comment by kremsy** [comment]
https://github.com/ManiaControl/ManiaControl/issues/139

**Comment by frozing** [comment]
ok thank you for you prompt reponse
