### ISSUE TITLE
Dedimania not updating properly

### ISSUE THREAD

**Issue by jakvrh1** [ManiaControl/ManiaControl#158]
Sometimes when you get dedi record your times won't be saved! You should try this out on map that has no records yet and see it yourself. Thanks for fixing in advance!

**Comment by kremsy** [comment]
Are you on the newest version of ManiaControl and the dedicated server? Is there anything in the maniacontrol log?

**Comment by jakvrh1** [comment]
I'm on the newest version 0.225(just did //coreupdate to be sure). This error is common for most maniacontrol servers not just on my server. I will do some extra pictures in a moment to show you what's happening.

**Comment by kremsy** [comment]
Interesting would be MC logs, if something wents wrong it should be in there. Thanks for the report, its weired we tested and thought everything works now.

**Comment by jakvrh1** [comment]
Is there a way to get in contact with you easier? Do you use discord or skype? If its possible I would like to help you sort this out as soon as possible because many players get annoyed by it.

**Comment by kremsy** [comment]
Write me Discord (kremsy)

**Comment by jakvrh1** [comment]
I need 4 digits example jaka#6308

**Comment by kremsy** [comment]
Paragon Luké#2591
