### ISSUE TITLE
Dedimania Plugin Error

### ISSUE THREAD

**Issue by acorecrack** [ManiaControl/ManiaControl#160]
huhu

i have a Problem that the new dedis dont save on some maps

here smth out of my maniacontrol.log

string(16) "Dedimania Debug:"
string(355) "<h1>Error 400: Bad Request</h1>
<br>
Request host: dedimania.net:8082
<br>
Request path: /Dedimania (POST /Dedimania HTTP/1.1)
<br>
Request agent: ManiaControl v0.226
<br>
Request error: <h1>Error 400: Bad Request</h1>
<br>
Request host: dedimania.net:8082
<br>
Request path: /Dedimania (POST /Dedimania HTTP/1.1)
<br>
Request agent: ManiaControl v0.226

"

mfg
Crack

**Comment by kremsy** [comment]
This is weired... First time i hear someone having this... Did they happen on different times or all at the same time (withij some minutes)? Do you have windows or linux servers? Do you have any special system configurations?

**Comment by acorecrack** [comment]
The servers run on a debian 64 bit system and i have no special configuration.

To the test I had even all servers except one switched off. Also the firewall I switched off shortly. The error only occurs with some maps, such as: https://tm.mania-exchange.com/tracks/104067/speedfun-illuminator-ax

I could also find in the maps no commonality.

**Comment by acorecrack** [comment]
I have looked at the log again and discovered another error.

17-Jul-2017 22:49:47 UTC] Dedimania Warning or Error: dedimania.SetChallengeTimes: "Warning in method_handler.php(467): Stadium is limited to maxrank 15 in TA for not upgraded servers! For premium accounts, see Dedimania forum and tm2stats page."

thats wrong ;) maxrank on non upgraded Server is 30

**Comment by kremsy** [comment]
This error is directly from dedimania, in stadium its 15, everywhere else 30. But that doesnt cause problems in time inserting. Did you had the first error only once or more often at different times?

**Comment by acorecrack** [comment]
i saw that error in the maniacontrol.log always after this map.... atm i saw that error twice

**Comment by kremsy** [comment]
We tried to reproduce it on the same map but we never got a Error 400.

**Comment by tomvlk** [comment]
@acorecrack @kremsy Do you have the exact time of this error? I saw some increase in error rates as well. It might be something related to Dedimania here, and I can help verify it.

**Comment by acorecrack** [comment]
[17-Jul-2017 13:21:13 UTC] and [18-Jul-2017 11:04:05 UTC]

**Comment by kremsy** [comment]
Closed for now, if it appears again please reopen.

**Comment by Nicklander** [comment]
I think I have the same issue, I opened a threat about it.
