### ISSUE TITLE
Display Authortime in the Map Widget

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#163]
Display the Authortime in Trackmania in the Map widget (without changing the size), make sure it doesnt make changes in shootmania.

**Comment by axelalex2** [comment]
https://i.imgur.com/4h966WB.png
This should be good. Every time can be enabled separately, as well as the timer icon will only appear, if there is a time to be displayed.

**Comment by kremsy** [comment]
Thanks! Maybe link commits to issues in future.

**Comment by axelalex2** [comment]
True.
https://github.com/ManiaControl/ManiaControl/commit/981c21a7d4d80e930ff67d74096e336bd262db41
And a little extra backend, which was needed:
https://github.com/ManiaControl/ManiaControl/commit/14f0d9b20cc2beddfe3ad95e08fa6a975cf60bab

**Comment by axelalex2** [comment]
Fixed the UI for SM by resetting defaults.
bbdb638a9b8189d9c17d5a8c57c3e0b4e84cd7ad
