### ISSUE TITLE
Capability to write description for plugin settings

### ISSUE THREAD

**Issue by jonthekiller** [ManiaControl/ManiaControl#173]
I think it can be useful to be able to show a description for each plugin settings when we have the mouse on a setting name like we have inside the plugins list to download. This attribute should not be mandatory.

**Comment by axelalex2** [comment]
7c04504e6acddc77233340712a9c2dcb3ee8420a
We are now left with a lot of empty descriptions for MC and plugin settings, but at least they are available now.
