### ISSUE TITLE
Local Record Plugin doesn't update

### ISSUE THREAD

**Issue by nicogodet** [ManiaControl/ManiaControl#176]
Hello,

I recently download and install ManiaControl.
I activate the plugin and I do a race but when I finish, the plugin doesn't input my racetime.

The ManiaControl logs doesn't show any error : 

> [24-May-2018 14:41:34 UTC] Starting ManiaControl...
> [24-May-2018 14:41:34 UTC] Checking for minimum required PHP-Version 5.4 ... 7.1.17-1+020180505045738.17+stretch1.gbpde69c6 OK!
> [24-May-2018 14:41:34 UTC] Checking for installed MySQLi ... FOUND!
> [24-May-2018 14:41:34 UTC] Checking for installed cURL ... FOUND!
> [24-May-2018 14:41:34 UTC] Checking for installed PHP ZIP ... FOUND!
> [24-May-2018 14:41:34 UTC] Checking for installed Zlib ... FOUND!
> [24-May-2018 14:41:34 UTC] Checking for installed mbstring ... FOUND!
> [24-May-2018 14:41:34 UTC] Loading ManiaControl v0.229 ...
> [24-May-2018 14:41:34 UTC] Starting ManiaControl v0.229!
> [24-May-2018 14:41:34 UTC] Connecting to Server at 127.0.0.1:5000...
> [24-May-2018 14:41:34 UTC] Server Connection successfully established!
> [24-May-2018 14:41:35 UTC] [INFO] Server Options successfully loaded!
> [24-May-2018 14:41:35 UTC] Checking Plugins for newer Versions...
> [24-May-2018 14:41:35 UTC] Loading completed!
> [24-May-2018 14:41:35 UTC] Link: maniaplanet://#join=USER@TMStadium@nadeo
> [24-May-2018 14:41:35 UTC] Plugins Update Check completed: All Plugins are up-to-date!
> ...
> [24-May-2018 14:44:54 UTC] [INFO] hapex activated 'MCTeam\LocalRecordsPlugin'!
> ...

The truth is I'm using mySQL but MariaDB, does it could a problem ?

Nicolas

**Comment by axelalex2** [comment]
Hello, i'm new in this project, currently cleaning up a lot of stuff. I hope you got around that issue, if not and you still got that issue, i would like to hear about it. Otherwise i will close this issue soon.

**Comment by axelalex2** [comment]
Closed off because of no response.

**Comment by NicoMigenda** [comment]
Hello,

I am having the same problem. Is there any info if Maniacontrol works with mariadb?
