### ISSUE TITLE
Activation/Installation of Plugins possible for minimum Moderators

### ISSUE THREAD

**Issue by axelalex2** [ManiaControl/ManiaControl#177]
When testing a private custom plugin, we found out, that a moderator can (de-)activate, install and view all settings of plugins, regardless of the given permissions in the AuthenticationManager (every permission was set to atleast "Admin", but a moderator was still able to do this stuff).

Furthermore, the admin panel doesn't hide, if the admin rights of a player will be removed, so he is still able to see all plugin settings.

This is a very important issue for us personally, since we won't be able to run tournaments the way we want, if this issue is unresolved.

**Comment by kremsy** [comment]
Weired issue, you sure you use the newest version of ManiaControl?

**Comment by axelalex2** [comment]
Using 0.229, so the newest.
After rejoining everything is fine. Just need to reevaluate the available commands for a player after removing admin rights from him, for this issue.

**Comment by kremsy** [comment]
The icon still does not dissapear right?`It must have todo with the "new" sidebar manager jocy created some months ago. Probably just a method call for redrawing is missing, sadly don't have enough time atm to investigate it.

**Comment by kremsy** [comment]
do the issue still exist?

**Comment by axelalex2** [comment]
The not disappearing icon? Yeah, i didn't bother checking so far, but i will now.
