### ISSUE TITLE
[enhancement] Add backgrounds to the widgets

### ISSUE THREAD

**Issue by J5lx** [ManiaControl/ManiaControl#18]
Since the widgets have no (visible?) backgrounds ATM, I’d propose to add such. This comes in handy when the background is similar to the widget contents as seen on the following screenshot in the top right corner, where the title of the Local Records widget isn’t visible:

![A04-Acrobatic](http://www.enlightenment.org/ss/e-53ca900b5cfcb0.00269493.png)

**Comment by kremsy** [comment]
As I know you can set in the Stylemanager a different Design for the Widget-Background.
