### ISSUE TITLE
Add missing Country in Formatter.php file

### ISSUE THREAD

**Issue by jonthekiller** [ManiaControl/ManiaControl#183]
Some country are missing inside the Formatter.php file like 'South Korea' (KOR), 'Vatican City' (VAT), 'Bosnia and Herzegovina' (BIH), 'Saint Lucia' (LCA) This list is probably not exhaustive.

I have a lot of warning message and I think give bad performance with a lot of players.

**Comment by kremsy** [comment]
Thanks for the report, feel free to make a pull request, than i merge it!
