### ISSUE TITLE
Pull request to add a ServerUI-Page in the Configurator

### ISSUE THREAD

**Issue by axelalex2** [ManiaControl/ManiaControl#193]
I saw, that it is possible to edit the builtin UIProperties of MP through FML, so you could write a plugin for it. But i'd rather see it as a permanent feature of MC.

Currently, the ServerUIPropertiesMenu.php works rather generically with the callbacks Callback::SM_UIPROPERTIES and Callback::TM_UIPROPERTIES, the deep-array on those callbacks get flattened for the menu. Editing all those properties for your server becomes a piece of cake then.

In some modes, some UIProperties seem to be unchangeable, but still appear in the menu for now.

Please let me know what you think about it.

**Comment by kremsy** [comment]
Heyho, I tested your change but there are some cosmetic problems
![grafik](https://user-images.githubusercontent.com/2006941/50728768-8be9c800-112f-11e9-9892-0e4fac6d6398.png)

Could you please fix that? After I can release the update.

**Comment by axelalex2** [comment]
Well, we could extend the height of the configurator, or lower the spacing between the menu points by a little. Personally, i've set the configurator height to 90 in my installed MC instances.
I can put one of those 2 solutions into the code, whichever you like more.

**Comment by kremsy** [comment]
Please stay with the standart height and less spacing, with a option to have it changable in the settings.

**Comment by axelalex2** [comment]
The spacing between the menu items was strictly set to 10 by code. For the current fix, i just lowered it to 9 by code, which would make it work, but it would not be editable by settings. I could add that, if you want me to.

**Comment by kremsy** [comment]
Thanks I will check it soon and than release the update. Im unsure if a setting is necessary, maybe the height of the widget could be used to calculate the spacing dynamically.
