### ISSUE TITLE
AsynchronousFileReader : Post data not sent ? 

### ISSUE THREAD

**Issue by MarlBurroW** [ManiaControl/ManiaControl#20]
Hi,

I don't think it's really an issue but i'm trying to post some data on my webservice using the AsynchronousFileReader class but no data are sent in the request.

I don't know if I use the right way to do that :

$data = array(/*data*/);
$postData =  http_build_query($data);

$this->maniaControl->fileReader->postData(self::OBSMANIA_URL . '/remote/' . $remoteMethod, $myCallBack, $postData, false);

Curl extension is enabled on my env.

Thanks !

**Comment by kremsy** [comment]
Does it work fine now? If no reopen the commit, if yes it would be good if you could tell us what you made wrong.
