### ISSUE TITLE
matchsettings problem multiple servers with MapManager.php

### ISSUE THREAD

**Issue by BestNoob** [ManiaControl/ManiaControl#201]
You need to change Line 132 in MapManager.php if you want to use another matchsettings file than tracklist.txt

`		$this->maniaControl->getSettingManager()->initSetting($this, self::SETTING_MAPLIST_FILE, "MatchSettings/NEWMATCHSETTINGSFILE.txt");`

**Comment by kremsy** [comment]
No you can change it via ingame setting, this line just says the default value for this setting. 

Just open in the game the Settings Menu, and Check at (MatchSettings Manager ? not exactly sure how its called there).

**Comment by BestNoob** [comment]
> 
> 
> No you can change it via ingame setting, this line just says the default value for this setting.
> 
> Just open in the game the Settings Menu, and Check at (MatchSettings Manager ? not exactly sure how its called there).

Ah okay, didnt recognized that. But when you did not changed this before you start the server, your old tracklist.txt is overwritten.
