### ISSUE TITLE
Maniacontrol random crash

### ISSUE THREAD

**Issue by floteix** [ManiaControl/ManiaControl#204]
Hello,

I'm configuring a dedicated server with ManiaControl, everything worked fine, ManiaControl runs on the server but I have a problem, after about a day, maniacontrol crash alone, and i don't know why

My error:
CODE

`[05-Jan-2019 15:53:16 UTC] [INFO] Player left: sungz / Jaja Playtime: 00:07:26
[05-Jan-2019 15:53:16 UTC] [INFO] Debug: Dedimania Player removed

Fatal error: Maximum execution time of 40 seconds exceeded in C:\Users\Florent.DESKTOP-20H1FVA\Desktop\Trackmania Server Entreprise\Serveur 4\core\Utils\SystemUtil.php on line 220
[05-Jan-2019 16:46:36 UTC] [PHP ERROR]: Maximum execution time of 40 seconds exceeded
File&Line: C:\Users\Florent.DESKTOP-20H1FVA\Desktop\Trackmania Server Entreprise\Serveur 4\core\Utils\SystemUtil.php: 220
[05-Jan-2019 16:46:36 UTC] Error-Report successful!
[05-Jan-2019 16:46:36 UTC] Quitting ManiaControl after Fatal Error.`

I'm working on a server hosting service and it's very hassle.

Plz help me  :?  :? 

My discord: FTV.FuroX#5748

**Comment by axelalex2** [comment]
I hope you have resolved the issue already? If not, i am here to help out now.

**Comment by axelalex2** [comment]
Closed off because of no answer.
