### ISSUE TITLE
StatisticManager warning with PHP 7.3

### ISSUE THREAD

**Issue by jonthekiller** [ManiaControl/ManiaControl#216]
I test ManiaControl with PHP 7.3 and I saw a warning during the initial loading:

`"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`

I found a RFC on PHP website telling that "continue" is deprecated: https://wiki.php.net/rfc/continue_on_switch_deprecation

**Comment by kremsy** [comment]
Merged your commit, but please review my idea to it.
