### ISSUE TITLE
Callbacks with OnWayPointEventStructure are broken on Windows

### ISSUE THREAD

**Issue by axelalex2** [ManiaControl/ManiaControl#219]
When testing a plugin on a windows-based server, all callbacks regarding WayPoint-Events were not triggered, while they completely work on unix-based servers. I couldn't immediately find the cause of this issue to fix it, but at least for the Checkpoints i could confirm them.
Other Callbacks might be broken in a similar fashion.

**Comment by kremsy** [comment]
Interesting, would be great if it could be verified.

**Comment by axelalex2** [comment]
With 9a7952811a93d50feb797349b9b789a9a3dfed35 , 0db1636a38cf6e3e5f3b43e8c0b4f5a8ef7eaea0 & 860678e57f584d8b0c661c969950eeda016eebd2 this is actually solved. The issue was not Windows itself, but that i never activated the LocalRecordsPlugin on the Windows Server, which listens to the Waypoint-Callback. The Waypoint-Callback also has the feature, that it splits into more specific callbacks, if the player finishes a lap/run. Unfortunately, if nothing listens to the Waypoint-Callback, the Finish-Callback didn't get triggered either.
I need to make some followup-tests on the default plugins, which react to those callbacks (most importantly Locals and Dedis).
