### ISSUE TITLE
Looking for someone to slowly take over the project.

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#220]
I sadly don't have time anymore for this project, I will look into it from time to time and contribute. Maybe someone else with great coding experience and time is willing to take over some parts and try to improve ManiaControl.

What is needed
-> Code Verification and Testing in order to Merge it into the master branch
-> Managing Github Issues
-> Looking into reoccuring errors from the error report on the MC website and fix them
-> If tests run well (Both SM and TM) new versions can be released (This will still be my part for now as a lot can go wrong with that)

**Comment by axelalex2** [comment]
Hey kremsy, i wanted to contact you in different ways, i missed this issue tho. So yeah, i already implemented a couple new features in my own fork, mainly used for the KnockOutPlugin by TrackMania Masters, so i know my way around the ManiaControl-core.
Working as main dev would be awesome, as i think there are a couple things to improve in this controller, and of course take actions to solve reported issues. Unfortunately, i don't possess ShootMania, so i cannot help out with that, but i think i still could help out a lot on the TrackMania side of things.
My contacts outside of Github, Mail: axelalex2 [at] gmx [dot] de // and Discord: axelalex2 [number sign] 5793. It would be awesome to hear back from you.

**Comment by kremsy** [comment]
Thanks for your help :)
