### ISSUE TITLE
LocalRecordsCPLive unload after every restart of server

### ISSUE THREAD

**Issue by Kaquaoify** [ManiaControl/ManiaControl#225]
I use LocalRecordsCPLivePlugin on a v231 server, and I just finish configure it.

It works, no problems, but when i do a restart of MC or server, the plugin auto-disable and lose all the configuration. 

How can i resolve that ?

**Comment by jonthekiller** [comment]
Have you check the ManiaControl logs? I only see this kind of things when I develop and change the version (not always).

**Comment by Kaquaoify** [comment]
- [INFO] kaquaoify activated 'Drakonia\LocalRecordsCPLivePlugin'!
- Can load LRCPLive plugin
- Can load LRCPLive Dedimania plugin

In the logfile of MC I have only this. 
When i launch the plugin, everything works, but when i restart, poof, disappear...
And look at the start sequence, nothing unload them.

> [15-Jul-2019 22:10:29 Europe/Berlin] Starting ManiaControl...
> 15-Jul-2019 22:10:29 Europe/Berlin] Checking for minimum required PHP-Version 5.4 ... 7.2.19-1+ubuntu18.04.1+deb.sury.org+1 OK!
> [15-Jul-2019 22:10:29 Europe/Berlin] Checking for installed MySQLi ... FOUND!
> [15-Jul-2019 22:10:29 Europe/Berlin] Checking for installed cURL ... FOUND!
> [15-Jul-2019 22:10:29 Europe/Berlin] Checking for installed PHP ZIP ... FOUND!
> [15-Jul-2019 22:10:29 Europe/Berlin] Checking for installed Zlib ... FOUND!
> [15-Jul-2019 22:10:29 Europe/Berlin] Checking for installed mbstring ... FOUND!
> [15-Jul-2019 22:10:29 Europe/Berlin] Loading ManiaControl v0.231 ...
> [15-Jul-2019 22:10:29 Europe/Berlin] Starting ManiaControl v0.231!
> [15-Jul-2019 22:10:29 Europe/Berlin] Connecting to Server at 127.0.0.1:11570...
> [15-Jul-2019 22:10:29 Europe/Berlin] Server Connection successfully established!
> [15-Jul-2019 22:10:30 Europe/Berlin] [INFO] Script Callbacks successfully enabled!
> [15-Jul-2019 22:10:30 Europe/Berlin] [INFO] Server Options successfully loaded!
> [15-Jul-2019 22:10:31 Europe/Berlin] [INFO] Try to connect on Dedimania
> [15-Jul-2019 22:10:31 Europe/Berlin] Checking Plugins for newer Versions...
> [15-Jul-2019 22:10:31 Europe/Berlin] Loading completed!
> [15-Jul-2019 22:10:31 Europe/Berlin] Link: maniaplanet://#join=ak-short_lol@TMStadium@nadeo
> [15-Jul-2019 22:10:32 Europe/Berlin] [INFO] Dedimania connection successfully established.
> [15-Jul-2019 22:10:32 Europe/Berlin] [INFO] Try to fetch Dedimania Records
> [15-Jul-2019 22:10:32 Europe/Berlin] [INFO] 4 Dedimania Records Fetched succesfully!
> [15-Jul-2019 22:10:32 Europe/Berlin] Plugins Update Check completed: All Plugins are up-to-date!
> [15-Jul-2019 22:10:32 Europe/Berlin] Successfully authenticated on Mania-Exchange Karma
> [15-Jul-2019 22:10:32 Europe/Berlin] [INFO] MX-Karma Votes successfully fetched

I have tested all the versions, even the .36 of today, but nothing changed

**Comment by jonthekiller** [comment]
It seems the activation is not saved in the database no? If you check inside the mc_plugins table, the active column should be at "1" for all activated plugins.

**Comment by Kaquaoify** [comment]
It's at 0. 
I try to put it manually at 1 and i will see.

**Comment by Kaquaoify** [comment]
So, when i load the plugin, tu sql value is 1.
But when I make a restart, ti changes the value for 0, but i don't know where and how....

**Comment by Kaquaoify** [comment]
The value is changed at 23h23m59s and in the log, Maniacontrol start at 23h24m00s. 

I have no logs to see what disable the plugin...

**Comment by Kaquaoify** [comment]
Here is what's inside my console log at the boot of my server

> [2019/07/15 23:23:36] Starting ManiaPlanet Date=2019-07-05_12_00 Svn=93845 GameVersion=3.3.0...
> [2019/07/15 23:23:36] Configuration file : dedicated_cfg.txt
> [2019/07/15 23:23:36] Loading system configuration...
> [2019/07/15 23:23:36] ...system configuration loaded
> [2019/07/15 23:23:36] Loading cache...
> [2019/07/15 23:23:36] ...OK
> [2019/07/15 23:23:37] Loading dedicated server configuration...
> [2019/07/15 23:23:37] ...Dedicated server configuration loaded
> [2019/07/15 23:23:37] Connecting to master server...
> [2019/07/15 23:23:37] ...OK
> [2019/07/15 23:23:37] Identifying on master server...
> [2019/07/15 23:23:37] ...OK
> [2019/07/15 23:23:38] Listening for xml-rpc commands on port 11570.
> [2019/07/15 23:23:38] Match settings file : MatchSettings\match_server_TMStadium_05074.txt
> [2019/07/15 23:23:38] Loading match settings...
> [2019/07/15 23:23:38] ...Match settings loaded
> [2019/07/15 23:23:38] Autostart server on internet
> [2019/07/15 23:23:38] URL: maniaplanet://#join=ak-short_lol@TMStadium@nadeo
> [2019/07/15 23:23:38] Starting server...
> [2019/07/15 23:23:38] Loading map 168924_-Minify_4.Map.Gbx (8eWxVhIXkRMOy4zvfXE7P1wjl0n)...
> [2019/07/15 23:23:38] ...Load succeeds
> [2019/07/15 23:23:38] Script 'Mode:TimeAttack': [LOG]1> [Log] Logs are disabled in the "production" environment.
> 
> [2019/07/15 23:23:40] Starting Match...
> [2019/07/15 23:23:40] ...Synchronization
> [2019/07/15 23:23:42] ...Play

**Comment by Kaquaoify** [comment]
It's ok now.
I just changed the name of the plugin and the folder and it stay activated.

I don't know where is the variable that say "you are desactivated, even if we told you to activate you" but i don't want to search further for that x)

Thanks for the help
