### ISSUE TITLE
57 out of 146 Plugins ?

### ISSUE THREAD

**Issue by BestNoob** [ManiaControl/ManiaControl#230]
Just recognized that ur website has listed 146 Plugins https://www.maniacontrol.com/plugins
but ingame via Admin Panel there just all about 57 available and 37 for downloading/installing also incompatible (outdated) ones for older MC. 

And on the Website its not clear which are only for Shootmania, Trackmania etc. no option for sorting/filter

Seems in ingame admin panel there also listed shootmania only plugins ....... while in TM ...

**Comment by Kaquaoify** [comment]
Is your server hosted on NC1.eu platform ?

If yes, the maniacontrol version that is pre-installed is in **v.231** and I didn't figured out how to upgrade it (and support didn't answer on my ticket...)

In the ManiaControl IG Panel, go to _**ManiaControl Settings > Plugins - InstallMenu**_ and check that the plugin installer only show what you can use (normally)

![11](https://user-images.githubusercontent.com/52884984/70855611-05587180-1ece-11ea-925d-efe5d24e80f2.PNG)
![22](https://user-images.githubusercontent.com/52884984/70855612-05587180-1ece-11ea-98f2-26ec14bd80fc.PNG)


If I found a way to upgrade ManiaControl, I come back to this issue

(sorry for english :-P)

**Comment by kremsy** [comment]
Some Plugins are not displayed because they are for old versions of ManiaControl / ManiaPlanet and have never been updated.
