### ISSUE TITLE
Plugin doesnt get deaktivated in Error / Exception case

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#243]
If an error / exception happens in a plugin, the plugin should disable itself before restarting ManiaControl, this system worked already in the past, something must have broken it.

It results in an indefinate restart loop.

**Comment by axelalex2** [comment]
https://github.com/ManiaControl/ManiaControl/blob/master/core/ErrorHandler.php#L133 this is the piece of code, which deactivates the plugin in case of a Fatal-Error, non Fatal-Errors do not result in a plugin deactivation, which is fine. But for some reason, on an exception, there is no plugin deactivation found anywhere.
I've added that in now: 8760364d826c72acb88346cc491a63a25ba09b9d
