### ISSUE TITLE
Plugin error with direct repo

### ISSUE THREAD

**Issue by LeGmask** [ManiaControl/ManiaControl#248]
If we use the official repo (git) and not the archive we can't install all the plugin in game (version error), if you could use an other branch and make pr when it's ready it would be nice 👍 !

**Comment by kremsy** [comment]
Hello, there are plugins which were made in the past but never updated (before mp4 update), thats why they cant be installed. try to reach the authors.

I highly dont recommend using any archiebed versions of maniacontrol as you will encounter lots of problems and bugs and incompatibilities with newer plugins. Dont use them!!!

**Comment by kremsy** [comment]
Or wait misunderstood.. you said all the plugins? any errors?

**Comment by LeGmask** [comment]
Hhm I have issue with almost all plugin, so yeah seems weird.

**Comment by LeGmask** [comment]
Okay maybad it's an issue from myself not from you sorry 👎
