### ISSUE TITLE
Don't display plugins which needs a too old MC version or sort them after the others

### ISSUE THREAD

**Issue by kremsy** [ManiaControl/ManiaControl#249]
![grafik](https://user-images.githubusercontent.com/2006941/79895711-9654d180-8407-11ea-9703-9c7cc7cd62d7.png)

**Comment by axelalex2** [comment]
There is already a setting for that in the ManiaControl-Settings, under "Plugins - InstallMenu", and it is enabled by default, but i didn't check, how far this affects the list actually.

**Comment by axelalex2** [comment]
Checked it now, and it only checks on the game. I guess a version-check would be a good 2nd setting to add to there.

**Comment by axelalex2** [comment]
I used a filter instead of a sorting option:
ab3e39086c55ac3f9c7ae032da6abdf3b1ffeff9
