### ISSUE TITLE
Getting a weird error - Return type of cURL\RequestsQueue::count() should either be compatible...

### ISSUE THREAD

**Issue by Schorschinger** [ManiaControl/ManiaControl#281]
hi :) when i start the bat i get a werid error. Log is attached.
can you help me?

greetings!
Noah :)

[ManiaControl_2023-04-20_9712.log](https://github.com/ManiaControl/ManiaControl/files/11290755/ManiaControl_2023-04-20_9712.log)

**Comment by kremsy** [comment]
I guess its some incompatibility with php8, could you try php7?

**Comment by Schorschinger** [comment]
Yep, it works with an older version of php. Thanks!!!
