### ISSUE TITLE
Allow changing the color of the join messages

### ISSUE THREAD

**Issue by steeffeen** [ManiaControl/ManiaControl#33]
requested by a user

**Comment by axelalex2** [comment]
I assume, that the color either should be a simple change, or could depend on the authentication level of a player, which i find a bit nicer.

**Comment by axelalex2** [comment]
Added colors to the Chat-Class now, so far it is only used for Join-/Leave-Messages tho.

**Comment by axelalex2** [comment]
https://github.com/ManiaControl/ManiaControl/commit/ae3d1d69dafb7ce5ea81d907c81770c4ddf7d8a3

**Comment by axelalex2** [comment]
TODO Move settings to new ColorManager, disable coloring on Join-/Leave by default.

**Comment by axelalex2** [comment]
165fec331708fad6625572df48f13b5be19590f0

**Comment by axelalex2** [comment]
96d0a1b5c9f0f79a1cb825c0aafceef368d7e3f4
