### ISSUE TITLE
Add "mbstring" to list of required extensions

### ISSUE THREAD

**Issue by Chris92de** [ManiaControl/ManiaControl#34]
Quoting from PHP.net:
"mbstring is a non-default extension. This means it is not enabled by default. You must explicitly enable the module with the configure option."

Required for function mb_check_encoding() in Connection.php line 4253

Discovered this while I started with a barebones compiled version of PHP5.6.6 on Ubuntu 12.04 with only curl and mysqli extension enabled during compilation.

This is most likely enabled by default in most PHP configurations anyways, but if you compile PHP yourself you will need this extension.

**Comment by kremsy** [comment]
Thanks for the report, the question is if this is even needed in the connection, could make a request on the dedicated api that they remove it, otherwise we will add it to our default extension list.

**Comment by NewboO** [comment]
Hi.

As the way mb_check_encoding was used could be done with a preg_match, it's now replaced to avoid this dependency. :)

**Comment by Chris92de** [comment]
Great, thanks NewboO :)

**Comment by kremsy** [comment]
Thank you very much, will forge the change in tomorrow or something :)

**Comment by kremsy** [comment]
Updated in commit: https://github.com/ManiaControl/ManiaControl/commit/8011ce4adfe258e57f4f8bd14dad57e6e97251c2
