### ISSUE TITLE
Add "zlib" to list of requires extensions (Linux only)

### ISSUE THREAD

**Issue by Chris92de** [ManiaControl/ManiaControl#37]
Hello,
zlib is not a default extension when you compile PHP  (enable with --with-zlib=[DIR] and --enable-zip options for ./configure)

Please add this to the list of required extensions, as it is needed by the auto updater.

**Comment by kremsy** [comment]
I added it to the extension list, but didn't have time to test it on a Linux machine yet, can you test it? (it's only here on git yet)
