### ISSUE TITLE
Votes won't be updated after submitted to MXKarma

### ISSUE THREAD

**Issue by Chris92de** [ManiaControl/ManiaControl#38]
Hello,
if a player votes on a map which is on MX and changes his mind on how he rates the track later, the updated vote won't be sent to MXKarma for whatever reason.
When the map gets played next time, it just overwrites the votes with the ones from MXKarma again.
Fix pls?

**Comment by kremsy** [comment]
It should definitly not be the case, I will investigate it.

**Comment by Chris92de** [comment]
We just tested it on a Royal map, it's definitely the case that the karma vote won't be updated.

**Comment by Chris92de** [comment]
Okay, we just figured out that it won't work if you change the Karma settings to allow +++ and ---.
Those votes won't be reflected, kind of changing the value on the MXKarma website then.

**Comment by kremsy** [comment]
It is definitly a bug, we tested everything only with ++ / --, the change of the Setting got made by steeffeen and he is very inactive at the moment, I don't have a lot time to fix that. Please use only the default setting.
