### ISSUE TITLE
Information needed

### ISSUE THREAD

**Issue by Willena** [ManiaControl/ManiaControl#46]
Hi !
I am curently trying to create a plugin, for the Elite mode of shootmania, for my server.

Everything is working as I want,  exept for the ending the warmup automaticaly, by my plugin.
When I click on the button it is okay, and when I a using this line ( in PHP ):
```
$this->maniaControl->getClient()->triggerModeScriptEvent('WarmUp_Stop', '');
```
it does not work. If what I am doing goes wrong can you explain to me how to get the warmup-en command, working

Thanks in advance,

PS: sorry for my poor english, I am french ...

**Comment by kremsy** [comment]
Hello,  your code is definitly correct, checked it also in other parts of mc. Maybe are in mode 0? and have not 6 players than the command has no effect.

**Comment by Willena** [comment]
Okay, so the problem is somewhere else... My server is in mode 1 ( free ) , but yes we were 3-4 when I tested that. The only thing I don't understand, is why this not working, but this is what Mc is doing when we click on the green "play" button ( see image ) 
![mcwarmup](https://cloud.githubusercontent.com/assets/1786065/9598482/4d49a67c-508c-11e5-9e4b-3b3caf22dff0.png)
This button work at every moment, and what I want to do is "simulate" a clic on this button, or execute what this button do and in the mc code i found this : 
```
public function commandEndWarmup(array $callback, Player $player) {
		if (!$this->maniaControl->getAuthenticationManager()->checkPermission($player, self::SETTING_PERMISSION_HANDLE_WARMUP)
		) {
			$this->maniaControl->getAuthenticationManager()->sendNotAllowed($player);
			return;
		}

		try {
			$this->maniaControl->getClient()->triggerModeScriptEvent('WarmUp_Stop', '');
			$this->maniaControl->getChat()->sendInformation($player->getEscapedNickname() . ' stopped the WarmUp!');
		} catch (GameModeException $e) {
		}
	}

```
In my plugin I have the same function without the permission check, and I edited what to write in the chat.

So that is why I do not understand what is going wrong ....

**Comment by kremsy** [comment]
It should work and is with a quite huge propability a programming mistakte on your side, you made some chatlogs, you sure the method gets called?

**Comment by Willena** [comment]
Here is part of my code, I wan't to execute the stopWarmUp function at map begining 
```
 public function load(ManiaControl $maniaControl) {
        $this->maniaControl = $maniaControl;
        //Some code .
        $this->maniaControl->getCallbackManager()->registerCallbackListener(Callbacks::BEGINMAP, $this, 'stopWarmup');       
    }

public function stopWarmup()
    {
        $this->playerCount = $this->maniaControl->getPlayerManager()->getPlayerCount(true, false);
        if ($this->playerCount > 1)
        {
             $this->maniaControl->getClient()->autoTeamBalance();

              try {
                    $this->maniaControl->getClient()->triggerModeScriptEvent('WarmUp_Stop', '');
                    $this->maniaControl->getChat()->sendInformation('WarmUp stopped !');
              } catch (GameModeException $e) {
              }
       }
    }
```
In game when we are more than 1, when I switch the map, or restart it, I can see the message "WarmUp stopped" but I am still waiting for the match to start...

**Comment by kremsy** [comment]
Alright, I see your problem, I think its just the point, BeginMap is to early to stop it. Try to use MCs timermanager, make a oneTimeTimerListening which delays the comamnd by 5seconds or something.

**Comment by Willena** [comment]
Thank you ! I thought that the event BEGINMAP, was triggered when the map
was ready to play, not during "the loading" time. Now It should work ( I am
going to test that and see), thanks for all !

2015-09-01 18:50 GMT+02:00 Lukas Kremsmayr <notifications@github.com>:

> Alright, I see your problem, I think its just the point, BeginMap is to
> early to stop it. Try to use MCs timermanager, make a oneTimeTimerListening
> which delays the comamnd by 5seconds or something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ManiaControl/ManiaControl/issues/46#issuecomment-136791300>
> .
>



-- 
cordialement.

Villena Guillaume
DGIProject

**Comment by kremsy** [comment]
Alright, nice to hear that we could help you :).
