### ISSUE TITLE
Problem with "50k to 100k" server

### ISSUE THREAD

**Issue by cime62** [ManiaControl/ManiaControl#48]
Hello, we have a little problem with our server.

In fact, maniacontrol doesn't want to set the server as a 100k server.

The solution would be to reset the maniacontrol plugin... But I have great karma on maps ! and I would like to keep these karmas ( which are local). When I say good karma, it is because they are mostly about twenty votes for 95%  :+1: 

So I do not know if there is a solution to switch to 100k keeping our karma :(

UltraX

**Comment by kremsy** [comment]
Change the Ladderlimit in your dedicated cfg after having the permission from Nadeo, restart the Server and everything will be fine!

**Comment by cime62** [comment]
Eheh we already have the Nadeo's permission, and Ladderlimit is already changed x)

Server was already restart too :/

**Comment by kremsy** [comment]
Where exactly is the problem, maniacontrol has nothing todo.with ladderlimit, if its set in dedicated cfg but it shows wrong in mc serversettings and you cant change it you could try in database itself.

But im sure there is no problem as we have multiple 100k servers running as well
