### ISSUE TITLE
Latest auto update broke our servers

### ISSUE THREAD

**Issue by MissyMelissa** [ManiaControl/ManiaControl#49]
We are for some reason unable to use auto update (it crashes without a very useful error shown in log), so maybe this shouldn't be enabled by default?

**Comment by kremsy** [comment]
Well there must be a reason, we alwaye want to have all mcs on the newest version and never had problems with it. We always release updates on our nightly channel first and check if problems occur, it its all working the beta channel will get the update. You can turn off auto update in your updatemanager settings.

**Comment by MissyMelissa** [comment]
I assume the updatemanager settings are in the database? I decided to just nop it out in code so that it doesn't try updating across all our servers. I don't have much more info on the actual error, it basically just told me there was an error, nothing else. :woman_shrugging:

**Comment by kremsy** [comment]
Its just a setting in the ingame setting manager, you dont need to change any code or anything in the databse. Maybe you could tell me the login of your server so i cqn check if we got a error submitted. But I think you have maybe some missconfiguration, like wrong name of the startfile that the restart just crashed it, does the ingame command //restatt work?

**Comment by kremsy** [comment]
sry I ment the command //restart

**Comment by MissyMelissa** [comment]
Yes it said there were some errors reported, you should check if there's any for `miss_pursuit`.

**Comment by kremsy** [comment]
Could you tell me a time when it happened?

I see one report: 2017-02-01 19:41:56 Request too large 

-> but this has nothing TODO with updating, it was a crash happening during opening the directory browser

Another Report: 2017-01-03 20:55:07 Call XML not a proper XML-RPC call. error parsing "9223372036854775807": Numerical result out of range (34) 

-> a setting got set to this high number but it expects a range up to 34 max, good report, gonna fix that crashes on that place won't happen again in the future

**Comment by MissyMelissa** [comment]
Thanks, those are good fixes.
